name: apple_sign_in
description: Sign in With Apple for Flutter. Native API bindings and a Flutter implementation of the sign in button. 
version: 2.0.0
author: Tom Gilder <tom@gilder.dev>
homepage: https://github.com/tomgilder/flutter_apple_sign_in

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  plugin:
    androidPackage: dev.gilder.tom.apple_sign_in
    pluginClass: AppleSignInPlugin
